### ISSUE TITLE
Make global pre- and suffix

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-rcs-core#24]
Pre- and suffixes (PnS), should be set in `fillLibraries`. `selectorLibrary` constructor should additionally get `this.prefix` and `this.suffix`

PnS should **not** get set in `selectorLibrary.set`. PnS will be just appended in `selectorLibrary.get` or `selectorLibrary.getAll`

**todo:**

- [x] add global PnS in `selectorLibrary`
- [x] remove PnS in `selectorLibrary.setValue`
- [x] remove `compressedSelectorPlain`
- [x] add `setPrefix`, `setSuffix` in `selectorLibrary`
- [ ] remove PnS in `replace.css#getAttributeSelector`, use global PnS instead
- [x] remove `plainCompressed` option in `selectorLibrary.getAll`

**Motivation:**

get rid of options in `replace.css`
